name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    uses: lucaswerkmeister/m3api/.github/workflows/release.yaml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
